name: "Release"

on:
  release:
    types:
      - "published"

permissions: {}

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    permissions:
      contents: write
    steps:
      - name: "Checkout the repository"
        uses: "actions/checkout@v6.0.1"

      - name: "Adjust version number"
        shell: "bash"
        run: |
          yq -i -o json '.version="${{ github.event.release.tag_name }}"' \
            "${{ github.workspace }}/custom_components/affalddk/manifest.json"

      - name: "ZIP the integration directory"
        shell: "bash"
        run: |
          cd "${{ github.workspace }}/custom_components/affalddk"
          zip affalddk.zip -r ./

      - name: "Upload the ZIP file to the release"
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ github.workspace }}/custom_components/affalddk/affalddk.zip

      # - name: "ZIP the Entity Picture Images"
      #   shell: "bash"
      #   run: |
      #     cd "${{ github.workspace }}/images/affalddk"
      #     zip affalddk_images.zip -r ./

      # - name: "Upload the images ZIP file to the release"
      #   uses: softprops/action-gh-release@v2.2.0
      #   with:
      #     files: ${{ github.workspace }}/images/affalddk/affalddk_images.zip
